### PR TITLE
Update to serposcope 2.7.0

### PR DESCRIPTION
**Pull request by mavimo**
see https://github.com/serphacker/serposcope/issues/155

### CODE REVIEW

**Comment by mavimo** [comment]
@fr3nd ping

**Comment by fr3nd** [comment]
That's still a beta release. I will add it when it becomes stable :)

**Comment by mavimo** [comment]
@fr3nd is stable release (git tag), was just published in a separate path, now in the "official" download path ;)

**Comment by fr3nd** [comment]
Merged and tagged. The docker image should be available soon: https://hub.docker.com/r/fr3nd/serposcope/builds/

Thanks! 👍

**Comment by fr3nd** [comment]
I had to revert the change. Jar for 2.7.0 is still not available to download

**Pull request merged**
